### ISSUE TITLE
Having trouble forging a primitive data type

### ISSUE THREAD

**Issue by ikbenben** [adaptive-logic/forgery#18]
I have a Profile class that includes a number of boolean instance variables. Does Forgery not support primitive data types? I'm getting the following error when trying to forge the Profile class:

    java.lang.RuntimeException: java.lang.InstantiationException: boolean
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at uk.co.adaptivelogic.forgery.Forgery.forge(Forgery.java:58)
        at uk.co.adaptivelogic.forgery.Forgery.forge(Forgery.java:70)
        at uk.co.adaptivelogic.forgery.Forgery.forgeProperty(Forgery.java:86)
        at uk.co.adaptivelogic.forgery.Forgery.forgeProperties(Forgery.java:78)
        at uk.co.adaptivelogic.forgery.Forgery.forge(Forgery.java:51)
        at com.fitmo.android.processor.LoginProcessorTest.testProfileAlreadyExists(LoginProcessorTest.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
    Caused by: java.lang.InstantiationException: boolean
        at java.lang.Class.newInstance(Class.java:423)
        at uk.co.adaptivelogic.forgery.Forgery.forge(Forgery.java:49)
        ... 32 more
    Caused by: java.lang.NoSuchMethodException: boolean.<init>()
        at java.lang.Class.getConstructor0(Class.java:3074)
        at java.lang.Class.newInstance(Class.java:408)
        ... 33 more

**Comment by seize-the-dave** [comment]
Not right now Ben, but we're open to pull requests :)

**Comment by dgunthor** [comment]
Ben, could you use a Boolean and use auto boxing?

**Comment by ikbenben** [comment]
@dgunthor , yep, I thought of that too. I'm not a fan of using object versions of primitive types, especially just to satisfy a unit testing requirement. I will either take a look at providing a pull request to allow primitives or I will use the object version. Not critical yet

**Comment by dgunthor** [comment]
If I get some time next week I'll see if I can get primitives working

**Comment by seize-the-dave** [comment]
:thumbsup:

**Comment by dgunthor** [comment]
forgery will work for primitive types e.g. boolean if you provide a class to forge them e.g. Boolean - I've added an example in the branch "primitives-example" which is in a pull request to be merged...
